"""Create complete database schema with all 22 tables

Revision ID: cb288462f943
Revises: 9c6ddf613883
Create Date: 2025-11-16 20:10:19.647016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb288462f943'
down_revision: Union[str, Sequence[str], None] = '9c6ddf613883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_brands_is_active'), 'brands', ['is_active'], unique=False)
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('calendar_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'time_slot', name='calendar_availability_unique_datetime')
    )
    op.create_index('idx_calendar_availability_date_time', 'calendar_availability', ['date', 'time_slot'], unique=False)
    op.create_index('idx_calendar_availability_is_available', 'calendar_availability', ['is_available'], unique=False, postgresql_where='is_available = FALSE')
    op.create_index(op.f('ix_calendar_availability_date'), 'calendar_availability', ['date'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('id != parent_category_id', name='categories_no_self_reference'),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_display_order'), 'categories', ['display_order'], unique=False)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_parent_category_id'), 'categories', ['parent_category_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('gallery_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("media_type IN ('image', 'video')", name='gallery_posts_media_type_check'),
    sa.CheckConstraint("source_type IN ('instagram', 'tiktok', 'original')", name='gallery_posts_source_type_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gallery_posts_tags', 'gallery_posts', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_gallery_posts_is_featured'), 'gallery_posts', ['is_featured'], unique=False)
    op.create_index(op.f('ix_gallery_posts_media_type'), 'gallery_posts', ['media_type'], unique=False)
    op.create_index(op.f('ix_gallery_posts_published_at'), 'gallery_posts', ['published_at'], unique=False)
    op.create_index(op.f('ix_gallery_posts_source_type'), 'gallery_posts', ['source_type'], unique=False)
    op.create_table('promo_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("discount_type IN ('percentage', 'fixed')", name='promo_codes_discount_type_check'),
    sa.CheckConstraint('discount_value > 0', name='promo_codes_discount_value_check'),
    sa.CheckConstraint('max_discount_amount >= 0', name='promo_codes_max_discount_check'),
    sa.CheckConstraint('min_order_amount >= 0', name='promo_codes_min_order_check'),
    sa.CheckConstraint('usage_count >= 0', name='promo_codes_usage_count_check'),
    sa.CheckConstraint('usage_limit > 0', name='promo_codes_usage_limit_check'),
    sa.CheckConstraint('usage_limit IS NULL OR usage_count <= usage_limit', name='promo_codes_usage_check'),
    sa.CheckConstraint('valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from', name='promo_codes_date_range_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_promo_codes_valid_dates', 'promo_codes', ['valid_from', 'valid_until'], unique=False)
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_index(op.f('ix_promo_codes_is_active'), 'promo_codes', ['is_active'], unique=False)
    op.create_table('service_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_bride_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('base_maid_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('base_mother_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('base_other_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_maids', sa.Integer(), nullable=True),
    sa.Column('min_maids', sa.Integer(), nullable=True),
    sa.Column('includes_facial', sa.Boolean(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("package_type IN ('bridal_large', 'bridal_small', 'bride_only', 'regular', 'classes')", name='service_packages_type_check'),
    sa.CheckConstraint('base_bride_price >= 0', name='service_packages_bride_price_check'),
    sa.CheckConstraint('base_maid_price >= 0', name='service_packages_maid_price_check'),
    sa.CheckConstraint('base_mother_price >= 0', name='service_packages_mother_price_check'),
    sa.CheckConstraint('base_other_price >= 0', name='service_packages_other_price_check'),
    sa.CheckConstraint('duration_minutes > 0', name='service_packages_duration_check'),
    sa.CheckConstraint('max_maids > 0', name='service_packages_max_maids_check'),
    sa.CheckConstraint('max_maids IS NULL OR min_maids IS NULL OR max_maids >= min_maids', name='service_packages_maid_range_check'),
    sa.CheckConstraint('min_maids >= 0', name='service_packages_min_maids_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_packages_display_order'), 'service_packages', ['display_order'], unique=False)
    op.create_index(op.f('ix_service_packages_is_active'), 'service_packages', ['is_active'], unique=False)
    op.create_index(op.f('ix_service_packages_package_type'), 'service_packages', ['package_type'], unique=False)
    op.create_table('transport_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('transport_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('transport_cost >= 0', name='transport_locations_cost_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_name')
    )
    op.create_index(op.f('ix_transport_locations_is_active'), 'transport_locations', ['is_active'], unique=False)
    op.create_index(op.f('ix_transport_locations_is_free'), 'transport_locations', ['is_free'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('admin_role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(is_admin = FALSE AND admin_role IS NULL) OR (is_admin = TRUE AND admin_role IS NOT NULL)', name='users_admin_role_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.create_table('vision_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('interested_in_salon', sa.Boolean(), nullable=True),
    sa.Column('interested_in_barbershop', sa.Boolean(), nullable=True),
    sa.Column('interested_in_spa', sa.Boolean(), nullable=True),
    sa.Column('interested_in_mobile_van', sa.Boolean(), nullable=True),
    sa.Column('additional_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vision_registrations_barbershop', 'vision_registrations', ['interested_in_barbershop'], unique=False, postgresql_where='interested_in_barbershop = TRUE')
    op.create_index('idx_vision_registrations_salon', 'vision_registrations', ['interested_in_salon'], unique=False, postgresql_where='interested_in_salon = TRUE')
    op.create_index('idx_vision_registrations_spa', 'vision_registrations', ['interested_in_spa'], unique=False, postgresql_where='interested_in_spa = TRUE')
    op.create_index('idx_vision_registrations_van', 'vision_registrations', ['interested_in_mobile_van'], unique=False, postgresql_where='interested_in_mobile_van = TRUE')
    op.create_index(op.f('ix_vision_registrations_created_at'), 'vision_registrations', ['created_at'], unique=False)
    op.create_index(op.f('ix_vision_registrations_email'), 'vision_registrations', ['email'], unique=False)
    op.create_index(op.f('ix_vision_registrations_location'), 'vision_registrations', ['location'], unique=False)
    op.create_table('admin_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_activity_logs_details', 'admin_activity_logs', ['details'], unique=False, postgresql_using='gin')
    op.create_index('idx_admin_activity_logs_entity', 'admin_activity_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_admin_activity_logs_action'), 'admin_activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_activity_logs_admin_user_id'), 'admin_activity_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_activity_logs_created_at'), 'admin_activity_logs', ['created_at'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('guest_phone', sa.String(length=20), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('booking_time', sa.Time(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('num_brides', sa.Integer(), nullable=True),
    sa.Column('num_maids', sa.Integer(), nullable=True),
    sa.Column('num_mothers', sa.Integer(), nullable=True),
    sa.Column('num_others', sa.Integer(), nullable=True),
    sa.Column('wedding_theme', sa.String(length=255), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transport_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deposit_paid', sa.Boolean(), nullable=True),
    sa.Column('deposit_paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'deposit_paid', 'completed', 'cancelled')", name='bookings_status_check'),
    sa.CheckConstraint('\n            user_id IS NOT NULL OR\n            (guest_email IS NOT NULL AND guest_name IS NOT NULL AND guest_phone IS NOT NULL)\n            ', name='bookings_user_or_guest_check'),
    sa.CheckConstraint('deposit_amount >= 0', name='bookings_deposit_amount_check'),
    sa.CheckConstraint('deposit_amount IS NULL OR deposit_amount = ROUND(total_amount * 0.5, 2)', name='bookings_deposit_amount_check_50_percent'),
    sa.CheckConstraint('num_brides >= 0', name='bookings_num_brides_check'),
    sa.CheckConstraint('num_maids >= 0', name='bookings_num_maids_check'),
    sa.CheckConstraint('num_mothers >= 0', name='bookings_num_mothers_check'),
    sa.CheckConstraint('num_others >= 0', name='bookings_num_others_check'),
    sa.CheckConstraint('subtotal >= 0', name='bookings_subtotal_check'),
    sa.CheckConstraint('total_amount >= 0', name='bookings_total_amount_check'),
    sa.CheckConstraint('transport_cost >= 0', name='bookings_transport_cost_check'),
    sa.ForeignKeyConstraint(['location_id'], ['transport_locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['package_id'], ['service_packages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bookings_date_time', 'bookings', ['booking_date', 'booking_time'], unique=False)
    op.create_index(op.f('ix_bookings_booking_date'), 'bookings', ['booking_date'], unique=False)
    op.create_index(op.f('ix_bookings_booking_number'), 'bookings', ['booking_number'], unique=True)
    op.create_index(op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookings_guest_email'), 'bookings', ['guest_email'], unique=False)
    op.create_index(op.f('ix_bookings_location_id'), 'bookings', ['location_id'], unique=False)
    op.create_index(op.f('ix_bookings_package_id'), 'bookings', ['package_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('guest_phone', sa.String(length=20), nullable=True),
    sa.Column('delivery_county', sa.String(length=100), nullable=True),
    sa.Column('delivery_town', sa.String(length=100), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('promo_code_id', sa.UUID(), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_confirmed', sa.Boolean(), nullable=True),
    sa.Column('payment_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'payment_confirmed', 'processing', 'shipped', 'delivered', 'cancelled')", name='orders_status_check'),
    sa.CheckConstraint('\n            user_id IS NOT NULL OR\n            (guest_email IS NOT NULL AND guest_name IS NOT NULL AND guest_phone IS NOT NULL)\n            ', name='orders_user_or_guest_check'),
    sa.CheckConstraint('delivery_fee >= 0', name='orders_delivery_fee_check'),
    sa.CheckConstraint('discount_amount >= 0', name='orders_discount_amount_check'),
    sa.CheckConstraint('subtotal >= 0', name='orders_subtotal_check'),
    sa.CheckConstraint('total_amount >= 0', name='orders_total_amount_check'),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_guest_email'), 'orders', ['guest_email'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_payment_confirmed'), 'orders', ['payment_confirmed'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('inventory_count', sa.Integer(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            (discount_type IS NULL AND discount_value IS NULL) OR\n            (discount_type IS NOT NULL AND discount_value IS NOT NULL AND discount_value > 0) OR\n            (discount_type = 'percentage' AND discount_value <= 100)\n            ", name='products_discount_check'),
    sa.CheckConstraint('base_price >= 0', name='products_base_price_check'),
    sa.CheckConstraint('discount_value >= 0', name='products_discount_value_check'),
    sa.CheckConstraint('inventory_count >= 0', name='products_inventory_count_check'),
    sa.CheckConstraint('low_stock_threshold >= 0', name='products_low_stock_threshold_check'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('idx_products_inventory', 'products', ['inventory_count'], unique=False)
    op.create_index('idx_products_tags', 'products', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_products_base_price'), 'products', ['base_price'], unique=False)
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_is_featured'), 'products', ['is_featured'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('product_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_images_display_order', 'product_images', ['product_id', 'display_order'], unique=False)
    op.create_index('idx_product_images_is_primary', 'product_images', ['product_id', 'is_primary'], unique=False)
    op.create_index('idx_product_images_one_primary', 'product_images', ['product_id'], unique=True, postgresql_where='is_primary = TRUE')
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_type', sa.String(length=50), nullable=False),
    sa.Column('variant_value', sa.String(length=100), nullable=False),
    sa.Column('price_adjustment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inventory_count', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('inventory_count >= 0', name='product_variants_inventory_check'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'variant_type', 'variant_value', name='product_variants_unique'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_product_variants_is_active'), 'product_variants', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_variant_type'), 'product_variants', ['variant_type'], unique=False)
    op.create_table('product_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_videos_display_order', 'product_videos', ['product_id', 'display_order'], unique=False)
    op.create_index(op.f('ix_product_videos_product_id'), 'product_videos', ['product_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('admin_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('helpful_count >= 0', name='reviews_helpful_count_check'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='reviews_rating_check'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'user_id', name='reviews_unique_product_user')
    )
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_is_approved'), 'reviews', ['is_approved'], unique=False)
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('testimonials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_photo_url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('testimonial_text', sa.Text(), nullable=False),
    sa.Column('related_service_id', sa.UUID(), nullable=True),
    sa.Column('related_product_id', sa.UUID(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='testimonials_rating_check'),
    sa.ForeignKeyConstraint(['related_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_service_id'], ['service_packages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testimonials_display_order'), 'testimonials', ['display_order'], unique=False)
    op.create_index(op.f('ix_testimonials_is_approved'), 'testimonials', ['is_approved'], unique=False)
    op.create_index(op.f('ix_testimonials_is_featured'), 'testimonials', ['is_featured'], unique=False)
    op.create_index(op.f('ix_testimonials_rating'), 'testimonials', ['rating'], unique=False)
    op.create_table('wishlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='wishlists_unique')
    )
    op.create_index(op.f('ix_wishlists_product_id'), 'wishlists', ['product_id'], unique=False)
    op.create_index(op.f('ix_wishlists_user_id'), 'wishlists', ['user_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity > 0', name='cart_items_quantity_check'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', 'product_variant_id', name='cart_items_unique')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_variant_id', sa.UUID(), nullable=True),
    sa.Column('product_title', sa.String(length=500), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('discount >= 0', name='order_items_discount_check'),
    sa.CheckConstraint('quantity > 0', name='order_items_quantity_check'),
    sa.CheckConstraint('total_price >= 0', name='order_items_total_price_check'),
    sa.CheckConstraint('unit_price >= 0', name='order_items_unit_price_check'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_created_at'), 'order_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_created_at'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_wishlists_user_id'), table_name='wishlists')
    op.drop_index(op.f('ix_wishlists_product_id'), table_name='wishlists')
    op.drop_table('wishlists')
    op.drop_index(op.f('ix_testimonials_rating'), table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_is_featured'), table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_is_approved'), table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_display_order'), table_name='testimonials')
    op.drop_table('testimonials')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_is_approved'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_product_videos_product_id'), table_name='product_videos')
    op.drop_index('idx_product_videos_display_order', table_name='product_videos')
    op.drop_table('product_videos')
    op.drop_index(op.f('ix_product_variants_variant_type'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_is_active'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_index('idx_product_images_one_primary', table_name='product_images', postgresql_where='is_primary = TRUE')
    op.drop_index('idx_product_images_is_primary', table_name='product_images')
    op.drop_index('idx_product_images_display_order', table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_is_featured'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_index(op.f('ix_products_base_price'), table_name='products')
    op.drop_index('idx_products_tags', table_name='products', postgresql_using='gin')
    op.drop_index('idx_products_inventory', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_confirmed'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_guest_email'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_package_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_location_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_guest_email'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_number'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_date'), table_name='bookings')
    op.drop_index('idx_bookings_date_time', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_admin_activity_logs_created_at'), table_name='admin_activity_logs')
    op.drop_index(op.f('ix_admin_activity_logs_admin_user_id'), table_name='admin_activity_logs')
    op.drop_index(op.f('ix_admin_activity_logs_action'), table_name='admin_activity_logs')
    op.drop_index('idx_admin_activity_logs_entity', table_name='admin_activity_logs')
    op.drop_index('idx_admin_activity_logs_details', table_name='admin_activity_logs', postgresql_using='gin')
    op.drop_table('admin_activity_logs')
    op.drop_index(op.f('ix_vision_registrations_location'), table_name='vision_registrations')
    op.drop_index(op.f('ix_vision_registrations_email'), table_name='vision_registrations')
    op.drop_index(op.f('ix_vision_registrations_created_at'), table_name='vision_registrations')
    op.drop_index('idx_vision_registrations_van', table_name='vision_registrations', postgresql_where='interested_in_mobile_van = TRUE')
    op.drop_index('idx_vision_registrations_spa', table_name='vision_registrations', postgresql_where='interested_in_spa = TRUE')
    op.drop_index('idx_vision_registrations_salon', table_name='vision_registrations', postgresql_where='interested_in_salon = TRUE')
    op.drop_index('idx_vision_registrations_barbershop', table_name='vision_registrations', postgresql_where='interested_in_barbershop = TRUE')
    op.drop_table('vision_registrations')
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transport_locations_is_free'), table_name='transport_locations')
    op.drop_index(op.f('ix_transport_locations_is_active'), table_name='transport_locations')
    op.drop_table('transport_locations')
    op.drop_index(op.f('ix_service_packages_package_type'), table_name='service_packages')
    op.drop_index(op.f('ix_service_packages_is_active'), table_name='service_packages')
    op.drop_index(op.f('ix_service_packages_display_order'), table_name='service_packages')
    op.drop_table('service_packages')
    op.drop_index(op.f('ix_promo_codes_is_active'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_index('idx_promo_codes_valid_dates', table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_gallery_posts_source_type'), table_name='gallery_posts')
    op.drop_index(op.f('ix_gallery_posts_published_at'), table_name='gallery_posts')
    op.drop_index(op.f('ix_gallery_posts_media_type'), table_name='gallery_posts')
    op.drop_index(op.f('ix_gallery_posts_is_featured'), table_name='gallery_posts')
    op.drop_index('idx_gallery_posts_tags', table_name='gallery_posts', postgresql_using='gin')
    op.drop_table('gallery_posts')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_category_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_categories_display_order'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_calendar_availability_date'), table_name='calendar_availability')
    op.drop_index('idx_calendar_availability_is_available', table_name='calendar_availability', postgresql_where='is_available = FALSE')
    op.drop_index('idx_calendar_availability_date_time', table_name='calendar_availability')
    op.drop_table('calendar_availability')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_index(op.f('ix_brands_is_active'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
