"""add_makeup_classes_and_enrollments

Revision ID: cdc731822407
Revises: edc36b0ac615
Create Date: 2026-01-12 16:26:47.434681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc731822407'
down_revision: Union[str, Sequence[str], None] = 'edc36b0ac615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makeup_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skill_level', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('duration_hours', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('price_from', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_to', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('what_you_learn', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('requirements', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("skill_level IN ('beginner', 'intermediate', 'advanced')", name='makeup_classes_skill_level_check'),
    sa.CheckConstraint("topic IN ('bridal', 'everyday', 'special_effects', 'editorial', 'corrective', 'stage_theater', 'airbrush', 'contouring', 'eye_makeup', 'other')", name='makeup_classes_topic_check'),
    sa.CheckConstraint('duration_hours > 0', name='makeup_classes_duration_check'),
    sa.CheckConstraint('price_from IS NULL OR price_from >= 0', name='makeup_classes_price_from_check'),
    sa.CheckConstraint('price_to IS NULL OR price_from IS NULL OR price_to >= price_from', name='makeup_classes_price_range_check'),
    sa.CheckConstraint('price_to IS NULL OR price_to >= 0', name='makeup_classes_price_to_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_makeup_classes_level_topic', 'makeup_classes', ['skill_level', 'topic'], unique=False)
    op.create_index(op.f('ix_makeup_classes_display_order'), 'makeup_classes', ['display_order'], unique=False)
    op.create_index(op.f('ix_makeup_classes_is_active'), 'makeup_classes', ['is_active'], unique=False)
    op.create_index(op.f('ix_makeup_classes_is_featured'), 'makeup_classes', ['is_featured'], unique=False)
    op.create_index(op.f('ix_makeup_classes_skill_level'), 'makeup_classes', ['skill_level'], unique=False)
    op.create_index(op.f('ix_makeup_classes_slug'), 'makeup_classes', ['slug'], unique=True)
    op.create_index(op.f('ix_makeup_classes_topic'), 'makeup_classes', ['topic'], unique=False)
    op.create_table('class_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enrollment_number', sa.String(length=50), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('preferred_dates', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'contacted', 'confirmed', 'completed', 'cancelled')", name='class_enrollments_status_check'),
    sa.ForeignKeyConstraint(['class_id'], ['makeup_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_class_enrollments_class_status', 'class_enrollments', ['class_id', 'status'], unique=False)
    op.create_index(op.f('ix_class_enrollments_class_id'), 'class_enrollments', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_enrollments_created_at'), 'class_enrollments', ['created_at'], unique=False)
    op.create_index(op.f('ix_class_enrollments_email'), 'class_enrollments', ['email'], unique=False)
    op.create_index(op.f('ix_class_enrollments_enrollment_number'), 'class_enrollments', ['enrollment_number'], unique=True)
    op.create_index(op.f('ix_class_enrollments_status'), 'class_enrollments', ['status'], unique=False)
    op.create_index(op.f('ix_class_enrollments_user_id'), 'class_enrollments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_enrollments_user_id'), table_name='class_enrollments')
    op.drop_index(op.f('ix_class_enrollments_status'), table_name='class_enrollments')
    op.drop_index(op.f('ix_class_enrollments_enrollment_number'), table_name='class_enrollments')
    op.drop_index(op.f('ix_class_enrollments_email'), table_name='class_enrollments')
    op.drop_index(op.f('ix_class_enrollments_created_at'), table_name='class_enrollments')
    op.drop_index(op.f('ix_class_enrollments_class_id'), table_name='class_enrollments')
    op.drop_index('idx_class_enrollments_class_status', table_name='class_enrollments')
    op.drop_table('class_enrollments')
    op.drop_index(op.f('ix_makeup_classes_topic'), table_name='makeup_classes')
    op.drop_index(op.f('ix_makeup_classes_slug'), table_name='makeup_classes')
    op.drop_index(op.f('ix_makeup_classes_skill_level'), table_name='makeup_classes')
    op.drop_index(op.f('ix_makeup_classes_is_featured'), table_name='makeup_classes')
    op.drop_index(op.f('ix_makeup_classes_is_active'), table_name='makeup_classes')
    op.drop_index(op.f('ix_makeup_classes_display_order'), table_name='makeup_classes')
    op.drop_index('idx_makeup_classes_level_topic', table_name='makeup_classes')
    op.drop_table('makeup_classes')
    # ### end Alembic commands ###
