"""add custom location fields to bookings

Revision ID: edc36b0ac615
Revises: cb288462f943
Create Date: 2025-11-23 16:25:26.187934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc36b0ac615'
down_revision: Union[str, Sequence[str], None] = 'cb288462f943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('custom_location_address', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('custom_location_latitude', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('custom_location_longitude', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('custom_location_distance_km', sa.Float(), nullable=True))
    op.alter_column('bookings', 'location_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('idx_bookings_custom_location', 'bookings', ['custom_location_latitude', 'custom_location_longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bookings_custom_location', table_name='bookings')
    op.alter_column('bookings', 'location_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('bookings', 'custom_location_distance_km')
    op.drop_column('bookings', 'custom_location_longitude')
    op.drop_column('bookings', 'custom_location_latitude')
    op.drop_column('bookings', 'custom_location_address')
    # ### end Alembic commands ###
